import os
from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

def add_code_block(doc, code_text):
    # Add a paragraph with a specific style for code
    p = doc.add_paragraph()
    run = p.add_run(code_text)
    run.font.name = 'Courier New'
    run.font.size = Pt(9)
    p.paragraph_format.left_indent = Pt(20)

doc = Document()

doc.add_heading('Big Data Project: Complete Source Code Documentation', 0)
doc.add_paragraph('This document contains the complete source code utilized in the BigEarthNet Land Cover Classification project, along with technical explanations for each module.')
doc.add_page_break()

files_to_document = [
    {
        "title": "1. Local Data Sampling & Subset Creation",
        "path": "src/python/0_create_subset_from_archive.py",
        "explanation": "Because the original BigEarthNet dataset is over 80GB, processing it entirely on a local machine is extremely difficult. This script randomly samples the dataset to create a manageable 40,000-image subset, allowing us to build and test the Big Data pipeline locally without running out of disk space."
    },
    {
        "title": "2. Feature Extraction (Python/Rasterio)",
        "path": "src/python/2_extract_features.py",
        "explanation": "This script is responsible for local data preprocessing. It reads the raw .tif satellite images using Rasterio. Instead of using raw pixels, it mathematically calculates the Normalized Difference Vegetation Index (NDVI) and Normalized Difference Water Index (NDWI) using the Near-Infrared, Red, and Green bands. It also calculates the mean and standard deviation for the bands, aggregating everything into a highly compressed columnar Parquet file (features_40k.parquet) that is ready to be ingested into Hadoop."
    },
    {
        "title": "3. Distributed Cluster Configuration (Docker Compose)",
        "path": "docker-compose.yml",
        "explanation": "This YAML file defines the entire distributed infrastructure. It provisions a Hadoop Distributed File System (HDFS) consisting of 1 NameNode and 3 DataNodes. It also provisions an Apache Spark cluster (1 Master, 1 Worker with 2 cores and 4GB RAM). This ensures the ML pipeline runs in a true distributed Big Data environment rather than just a local Python script."
    },
    {
        "title": "4. Distributed Machine Learning (Scala / Spark MLlib)",
        "path": "src/main/scala/LandCoverClassifier.scala",
        "explanation": "This is the core Big Data processing script written in Scala. It reads the Parquet data directly from HDFS. It performs the required Spark preprocessing by using StringIndexer (to encode string labels into numeric indices) and VectorAssembler (to combine the 10 extracted features into a single dense vector). Finally, it trains a distributed Random Forest Classifier, evaluates the metrics, and saves the resulting predictions back into HDFS."
    },
    {
        "title": "5. Evaluation Metrics (Scikit-Learn)",
        "path": "src/python/3_evaluate_results.py",
        "explanation": "Once the Spark job finishes, the predictions are extracted from HDFS back to the local machine. This script uses Pandas and Scikit-Learn to map the numeric Spark predictions back to their original string labels. It then generates a detailed Classification Report and Confusion Matrix, exporting them as CSV files for visualization."
    },
    {
        "title": "6. Dashboard Visualization (Matplotlib/Seaborn)",
        "path": "generate_dashboard.py",
        "explanation": "This script serves as the final presentation layer. It reads the CSV metrics generated by the evaluation script and uses Seaborn to plot a high-resolution, side-by-side dashboard. The dashboard includes a heatmap of the Confusion Matrix and a bar chart of the F1-Scores for each land cover class, making the model's performance easily interpretable."
    }
]

base_dir = "C:/Users/sanji/Desktop/bda_project"

for file_info in files_to_document:
    doc.add_heading(file_info['title'], level=1)
    doc.add_paragraph(file_info['explanation'])
    
    file_path = os.path.join(base_dir, file_info['path'])
    
    if os.path.exists(file_path):
        doc.add_heading(f"File: {file_info['path']}", level=2)
        with open(file_path, 'r', encoding='utf-8') as f:
            code_content = f.read()
        
        # Docx has limits on single paragraph sizes, so we split by lines if it's too long
        add_code_block(doc, code_content)
    else:
        doc.add_paragraph(f"[Code file not found at {file_path}]")
        
    doc.add_page_break()

output_path = os.path.join(base_dir, "Code_Documentation.docx")
doc.save(output_path)
print(f"Successfully generated {output_path}")
